name: Bug Report
description: Report a bug or issue with Immich-Deduper
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight Checklist
      description: Please check the following before submitting your bug report
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guides
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: dropdown
    id: deployment-method
    attributes:
      label: Deployment Method
      description: How are you running Immich-Deduper?
      options:
        - Docker Compose (same-host with Immich)
        - Docker Compose (different-host from Immich)
        - Source Installation (pip install)
        - Development/Source (git clone)
      default: 0
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide your environment details
      placeholder: |
        OS: [e.g. Ubuntu 22.04, Windows 11, macOS 13]
        Python Version: [e.g. 3.11.5]
        Immich Version: [e.g. v1.95.1]
        Deduper Version: [e.g. 0.1.3]
        GPU: [e.g. NVIDIA RTX 4080, CPU only]
        Docker Version: [if using Docker]
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your configuration (remove sensitive data like passwords)
      placeholder: |
        Environment variables or config file content (with sensitive data removed):

        PSQL_HOST=localhost
        PSQL_PORT=5432
        PSQL_DB=immich
        PSQL_USER=postgres
        PSQL_PASS=***REMOVED***
        ...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please provide relevant error logs or stack traces
      placeholder: |
        Paste error logs here...

        You can find logs in:
        - Docker: docker compose logs mediakit
        - Source: data/logs/mediakit.log
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, additional logs, related issues, etc.
    validations:
      required: false

  - type: checkboxes
    id: system-specs
    attributes:
      label: System Specifications
      description: Please check all that apply to your system
      options:
        - label: Using GPU acceleration
        - label: Large dataset (>10k images)
        - label: Custom Qdrant configuration
        - label: External PostgreSQL database
        - label: Running behind proxy/reverse proxy
        - label: Using custom Docker configuration
